//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.PluginSdkDemo.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiyActivePedal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiyActivePedal() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("User.PluginSdkDemo.Language.DiyActivePedal", typeof(DiyActivePedal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Exponent 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextExponent {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Linear 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextLinear {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logarithm 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextLogarithm {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 S-Curve 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextSCurve {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextSCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cloud Config 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextGetOnlineConfig {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextGetOnlineConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pedal Info 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextGetPedalInfo {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextGetPedalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OTA 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextPedalOta {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextPedalOta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Retsart 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextPedalRestart {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextPedalRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serial Logs 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextSerialMonitor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextSerialMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pedal Roles 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextWirelessAssignment {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextWirelessAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Debug Flag 0: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelDebugFlag0 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelDebugFlag0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pedal Settings 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelPedalSetting {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelPedalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Advanced Mode 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAdvancedMode {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatic Com Connect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAutoComConnect {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAutoComConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatic Bridge Connect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAutoConnectBridge {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAutoConnectBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatic Profile Switch 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAutoProfileSwitch {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAutoProfileSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fanatec Or Pico Support 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingFanatecOrPicoSupport {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingFanatecOrPicoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Setting 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 vJoy Output 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingVjoyOutput {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingVjoyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CUSTOM1 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom1 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CUSTOM2 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom2 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CUSTOM3 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom3 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CUSTOM4 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom4 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filter 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextFilter {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 General 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextGeneral {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Global Effects 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextGlobalEffects {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextGlobalEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Servo 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextServo {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextApply {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Clear 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextAutoClear {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextAutoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatic Pedal Connect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextAutomaticPedalConnect {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextAutomaticPedalConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bridge 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBridgeId {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBridgeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bind 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBind {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bridge Debug 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBridgeDebug {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBridgeDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bridge OTA 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBridgeOTA {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBridgeOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restart 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBridgeRestart {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBridgeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnClear {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Plugin Update 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnPluginUpdate {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnPluginUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add new Config 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListAddNewConfig {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListAddNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListPreview {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Active Config 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListReset {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save as New Config 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListSaveAs {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set as Startup 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListSetAsStartup {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListSetAsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Config List 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDelete {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Apply By: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSEffectApply {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSEffectApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Profile: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSEffectProfile {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSEffectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simulate ABS 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSSimulateABS {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSSimulateABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ABS/TC Amplitude 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSSliderAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSSliderAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ABS/TC Frequency 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSSliderFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSSliderFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test ABS/TC 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSTestABS {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSTestABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ABS/TC Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bite Point Amplitude 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectBiteAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectBiteAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bite Point Frequency 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectBiteFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectBiteFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bite Point Vibration 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectBiteTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectBiteTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Effect 1 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom1Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom1Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Effect 2 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom2Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom2Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Effect 3 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom3Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom3Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Effect 4 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom4Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom4Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Amplitude 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustomAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustomAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Frequency 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustomFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustomFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Trigger 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustomTrigger {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustomTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Amplitude 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect depend: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineDepend {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineDepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Frequency: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Engine RPM 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineRPM {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Speed Rumble 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineSpeed {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Engine RPM / Speed Rumble Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 G Force Multiplier 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectGforceMultiplier {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectGforceMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 G Force Smoothness 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectGforceSmoothness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectGforceSmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 G-Force Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectGforceTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectGforceTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Impact Multiplier 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectImpactMultiplier {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectImpactMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Impact Smoothness 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectImpactSmoothness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectImpactSmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Road Impact Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectImpactTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectImpactTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acceleration Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectRudderAccTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectRudderAccTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wind Force Applied on Rudder 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectRudderAccWindForce {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectRudderAccWindForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Engine RPM Rumble Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectRudderEngineTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectRudderEngineTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effects Update Rate: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectUpdateRate {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notification Amplitude 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notification Frequency 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Effect Property 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipProperty {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wheel Slip Notification 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notification Trigger 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipTrigger {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FORCE CURVE ADJUSTMENT 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextForceCurveAdjustment {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextForceCurveAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FORCE-TRAVEL CURVE 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextForceTravelCurve {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextForceTravelCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 General Settings 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSetting {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable crash detect. 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingCrashDetect {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingCrashDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Damping Factor 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingDampingFactor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingDampingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Joystick output from travel 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingJoystickOutputFromTravel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingJoystickOutputFromTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Linear Module Pitch: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingLinearPitch {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingLinearPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loadcell Rate 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingLoadcellRate {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingLoadcellRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max Game Output 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingMaxGameOut {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingMaxGameOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reverse LC reading 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingReverseLCReading {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingReverseLCReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reverse Servo Direction 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingReverseServoDirection {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingReverseServoDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Servo Idle Timeout 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingServoIdleTimeout {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingServoIdleTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable step loss recov. 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingStepLossRecor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingStepLossRecor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Threshold Force for Effect 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGlobalEffectsSettingSliderEffectThresholdForce {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGlobalEffectsSettingSliderEffectThresholdForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Global Effects Setting 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGlobalEffectsSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGlobalEffectsSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JOYSTICK MAPPING 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMapping {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arrange in Exponential 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInExponential {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInExponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arrange in Line 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInLine {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arrange in Logarithm 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInLogarithm {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arrange in S Curve 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInSCurve {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInSCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JOYSTICK MAPPING 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filter Model: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingFilterModel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingFilterModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 KF for Joystick Denoise 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseSliderName {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseSliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Denoise for Joystick output 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseToggle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loadcell Denoising Factor (slow to fast) 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingKFDescription {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingKFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Noise Reduction Filter 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bridge Version 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelBridgeVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelBridgeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelConnection {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DAP Version 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelDAPVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelDAPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pedal Version 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelPedalVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelPedalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Plugin Version 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelPluginVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Servo State 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelServoState {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelServoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Leave without Change 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLeaveWithoutChange {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLeaveWithoutChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log Pedal States 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLogPedalStates {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLogPedalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Caution, the config and pedal kinematics may cause servo overloaded!! 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextOverloadWarning1 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextOverloadWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max servo output force 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextOverloadWarning2 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextOverloadWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Overwrite 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextOverwrite {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Brake 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalIdBrake {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalIdBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clutch 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalIdClutch {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalIdClutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Throttle 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalIdThrottle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalIdThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pedal Info 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalInfoTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PEDAL KINEMATICS 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematics {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pedal Kinematic calculation error 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematicsError {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Expected max force at max travel 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematicsExpectedMaxForce {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematicsExpectedMaxForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PEDAL KINEMATIC SETTING 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematicsTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PEDALS 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedals {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add new Profile 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListAddNewProfile {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListAddNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Game or Car ID: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListGameOrCar {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListGameOrCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save as New Profile 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListSaveAs {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile List 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile Binding 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutBinding {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Action Name 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutName {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile Shortcut 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 *The change of Custom Action Name will be applied after a simhub restart. 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutWarning {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRead {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refresh List 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRefreshList {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRename {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RUDDER 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRudder {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRudder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rudder 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRudderId {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRudderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rudder Info 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRudderInfoTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRudderInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Endstop Detection Threshold 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingSliderEndstopCurrent {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingSliderEndstopCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ratio of Inertia (Pr0.04) 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingSliderServoInertia {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingSliderServoInertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Servo position smoothing factor  (Pr2.22) 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingSliderServoSmoothness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingSliderServoSmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Servo Settings 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SYSTEM 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextSystem {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Info 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextSystemInfoTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextSystemInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Channel: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateChannel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Force Flash Firmware 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateForceFlash {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateForceFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload from PlatformIO 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateFromPlatformio {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateFromPlatformio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test Build DO NOT USE 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateTestBuildWarning {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateTestBuildWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PASS: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateWindowPass {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateWindowPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SSID: 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateWindowSSID {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateWindowSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Setting 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateWindowTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wireless Communication 的當地語系化字串。
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextWirelessCommunication {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextWirelessCommunication", resourceCulture);
            }
        }
    }
}
