//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.PluginSdkDemo.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiyFfbPedal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiyFfbPedal() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("User.PluginSdkDemo.Language.DiyFfbPedal", typeof(DiyFfbPedal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exponent ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextExponent {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linear ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextLinear {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logarithm ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextLogarithm {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S-Curve ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_BtnTextSCurve {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_BtnTextSCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cloud Config ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextGetOnlineConfig {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextGetOnlineConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pedal Info ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextGetPedalInfo {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextGetPedalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OTA ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextPedalOta {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextPedalOta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retsart ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextPedalRestart {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextPedalRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial Logs ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextSerialMonitor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextSerialMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pedal Roles ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_ButtonTextWirelessAssignment {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_ButtonTextWirelessAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Flag 0: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelDebugFlag0 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelDebugFlag0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pedal Settings ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelPedalSetting {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelPedalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Mode ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAdvancedMode {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Com Connect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAutoComConnect {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAutoComConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Bridge Connect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAutoConnectBridge {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAutoConnectBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Profile Switch ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingAutoProfileSwitch {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingAutoProfileSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fanatec Or Pico Support ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingFanatecOrPicoSupport {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingFanatecOrPicoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Setting ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vJoy Output ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_LabelSystemSettingVjoyOutput {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_LabelSystemSettingVjoyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CUSTOM1 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom1 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CUSTOM2 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom2 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CUSTOM3 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom3 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CUSTOM4 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabItemCustom4 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabItemCustom4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dynamics ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextDynamics {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextDynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextFilter {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextGeneral {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Effects ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextGlobalEffects {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextGlobalEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servo ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TabTextServo {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TabTextServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextApply {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Clear ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextAutoClear {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextAutoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Pedal Connect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextAutomaticPedalConnect {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextAutomaticPedalConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBridgeId {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBridgeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bind ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBind {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Debug ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBridgeDebug {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBridgeDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge OTA ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBridgeOTA {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBridgeOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnBridgeRestart {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnBridgeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnClear {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Editor ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnEditor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leave ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnLeave {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Update ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextBtnPluginUpdate {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextBtnPluginUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new Config ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListAddNewConfig {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListAddNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListPreview {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Active Config ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListReset {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as New Config ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListSaveAs {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as Startup ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListSetAsStartup {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListSetAsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config List ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextConfigListTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextConfigListTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDelete {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endstop Stiffness ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDynamicsSettingSliderEndstopStiffness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDynamicsSettingSliderEndstopStiffness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endstop Travel ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDynamicsSettingSliderEndstopTravel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDynamicsSettingSliderEndstopTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damping progression ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDynamicsSettingSliderPedalProgression {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDynamicsSettingSliderPedalProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual Pedal Damping (zeta value) ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDynamicsSettingSliderVirtualPedalDamping {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDynamicsSettingSliderVirtualPedalDamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual Pedal Mass ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextDynamicsSettingSliderVirtualPedalMass {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextDynamicsSettingSliderVirtualPedalMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Apply By: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSEffectApply {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSEffectApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Profile: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSEffectProfile {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSEffectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulate ABS ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSSimulateABS {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSSimulateABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABS/TC Amplitude ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSSliderAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSSliderAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABS/TC Frequency ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSSliderFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSSliderFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test ABS/TC ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSTestABS {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSTestABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABS/TC Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectABSTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectABSTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bite Point Amplitude ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectBiteAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectBiteAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bite Point Frequency ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectBiteFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectBiteFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bite Point Vibration ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectBiteTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectBiteTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Effect 1 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom1Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom1Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Effect 2 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom2Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom2Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Effect 3 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom3Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom3Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Effect 4 ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustom4Tittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustom4Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Amplitude ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustomAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustomAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Frequency ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustomFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustomFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Trigger ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectCustomTrigger {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectCustomTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Amplitude ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect depend: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineDepend {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineDepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Frequency: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engine RPM ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineRPM {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed Rumble ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineSpeed {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engine RPM / Speed Rumble Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectEngineTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectEngineTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G Force Multiplier ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectGforceMultiplier {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectGforceMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G Force Smoothness ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectGforceSmoothness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectGforceSmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G-Force Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectGforceTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectGforceTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impact Multiplier ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectImpactMultiplier {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectImpactMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impact Smoothness ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectImpactSmoothness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectImpactSmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Road Impact Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectImpactTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectImpactTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acceleration Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectRudderAccTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectRudderAccTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind Force Applied on Rudder ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectRudderAccWindForce {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectRudderAccWindForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engine RPM Rumble Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectRudderEngineTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectRudderEngineTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effects Update Rate: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectUpdateRate {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notification Amplitude ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipAmp {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notification Frequency ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipFreq {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Property ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipProperty {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wheel Slip Notification ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notification Trigger ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextEffectWheelSlipTrigger {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextEffectWheelSlipTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FORCE CURVE ADJUSTMENT ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextForceCurveAdjustment {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextForceCurveAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FORCE-TRAVEL CURVE ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextForceTravelCurve {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextForceTravelCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Settings ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSetting {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable crash detect. ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingCrashDetect {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingCrashDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damping Factor ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingDampingFactor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingDampingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Joystick output from travel ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingJoystickOutputFromTravel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingJoystickOutputFromTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linear Module Pitch: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingLinearPitch {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingLinearPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loadcell Rate ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingLoadcellRate {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingLoadcellRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Game Output ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingMaxGameOut {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingMaxGameOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverse LC reading ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingReverseLCReading {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingReverseLCReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverse Servo Direction ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingReverseServoDirection {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingReverseServoDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servo Idle Timeout ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingServoIdleTimeout {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingServoIdleTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable step loss recov. ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGeneralSettingStepLossRecor {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGeneralSettingStepLossRecor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threshold Force for Effect ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGlobalEffectsSettingSliderEffectThresholdForce {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGlobalEffectsSettingSliderEffectThresholdForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Effects Setting ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextGlobalEffectsSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextGlobalEffectsSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JOYSTICK MAPPING ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMapping {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrange in Exponential ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInExponential {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInExponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrange in Line ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInLine {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrange in Logarithm ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInLogarithm {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInLogarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arrange in S Curve ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingArrangeInSCurve {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingArrangeInSCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JOYSTICK MAPPING ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextJoystickMappingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextJoystickMappingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Model: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingFilterModel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingFilterModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KF for Joystick Denoise ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseSliderName {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseSliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Denoise for Joystick output ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseToggle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingJoystickDenoiseToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loadcell Denoising Factor (slow to fast) ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingKFDescription {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingKFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Noise Reduction Filter ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextKFSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextKFSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Version ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelBridgeVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelBridgeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelConnection {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DAP Version ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelDAPVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelDAPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pedal Version ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelPedalVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelPedalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Version ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelPluginVersion {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servo State ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLabelServoState {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLabelServoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leave without Change ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLeaveWithoutChange {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLeaveWithoutChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capture pedal trace ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextLogPedalStates {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextLogPedalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ncalc Script Editor ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextNcalcEditorTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextNcalcEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution, the config and pedal kinematics may cause servo overloaded!! ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextOverloadWarning1 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextOverloadWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max servo output force ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextOverloadWarning2 {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextOverloadWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextOverwrite {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brake ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalIdBrake {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalIdBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clutch ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalIdClutch {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalIdClutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Throttle ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalIdThrottle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalIdThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pedal Info ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalInfoTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PEDAL KINEMATICS ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematics {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pedal Kinematic calculation error ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematicsError {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematicsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected max force at max travel ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematicsExpectedMaxForce {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematicsExpectedMaxForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PEDAL KINEMATIC SETTING ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedalKinematicsTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedalKinematicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PEDALS ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextPedals {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextPedals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new Profile ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListAddNewProfile {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListAddNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game or Car ID: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListGameOrCar {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListGameOrCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as New Profile ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListSaveAs {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile List ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileListTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileListTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile Binding ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutBinding {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Action Name ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutName {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile Shortcut ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *The change of Custom Action Name will be applied after a simhub restart. ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextProfileShortcutWarning {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextProfileShortcutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRead {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh List ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRefreshList {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRename {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RUDDER ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRudder {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRudder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rudder ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRudderId {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRudderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rudder Info ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextRudderInfoTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextRudderInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endstop Detection Threshold ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingSliderEndstopCurrent {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingSliderEndstopCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ratio of Inertia (Pr0.04) ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingSliderServoInertia {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingSliderServoInertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servo position smoothing factor  (Pr2.22) ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingSliderServoSmoothness {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingSliderServoSmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servo Settings ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextServoSettingTittle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextServoSettingTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SYSTEM ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextSystem {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Info ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextSystemInfoTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextSystemInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Channel: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateChannel {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Force Flash Firmware ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateForceFlash {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateForceFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload from PlatformIO ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateFromPlatformio {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateFromPlatformio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Build DO NOT USE ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateTestBuildWarning {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateTestBuildWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PASS: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateWindowPass {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateWindowPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SSID: ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateWindowSSID {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateWindowSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Setting ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextUpdateWindowTitle {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextUpdateWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wireless Communication ähnelt.
        /// </summary>
        internal static string DIYFFBPedalPlugin_TextWirelessCommunication {
            get {
                return ResourceManager.GetString("DIYFFBPedalPlugin_TextWirelessCommunication", resourceCulture);
            }
        }
    }
}
