[env:esp32-s3-zero]
board = esp32-s3-devkitc-1
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
upload_protocol = esptool

framework = arduino
#platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip
#platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.3.0


; 1. Nutze den aktuellsten Entwicklungsstand der pioarduino-Plattform anstelle der statischen ZIP
#platform = https://github.com/pioarduino/platform-espressif32.git
; 2. Ziehe den absoluten Master-Branch (die aktuellsten Commits von heute) des offiziellen Espressif-Cores
#platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#master

platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
#platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.4.0

monitor_speed = 115200

build_unflags = -DARDUINO_USB_MODE=1
build_flags = 
    -O3
    -DARDUINO_RUNNING_CORE=1
    -DCORE_DEBUG_LEVEL=0
    -DUSE_TINYUSB=1
    -DARDUINO_USB_MODE=0 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DPCB_VERSION=14
    -DUSB_JOYSTICK

; lib_deps komplett entfernt, da nun die Core-Implementierung genutzt wird